#应用名称
spring:
  application:
    name: lfp-admin-client
  boot:
    admin:
# 注入的接口监控
      url: http://localhost:9000
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
# 端口
server:
  port: 9001
#  调试阶段，关闭安全验证
management:
  security:
    enabled: false
#    info信息
info:
  app:
#  项目名称
    name: "@project.name@"
    description: "@project.description@"
    spring-boot-version: "@project.parent.version@"
  build:
    version: "@project.version@"
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
      web: DEBUG