spring:
  application:
    name: lfp-eureka-server
server:
  port: 8761
eureka:
  client:
#  配置不进行自我注册核信息拉取
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  server:
#   是否打开自我保护，如果设置为true，很容易会出现红色字体的自我保护提示，不方便测试
    enable-self-preservation: false
#   清理时间，默认是60*1000毫秒，修改短一点，保证开发时，客户端失效后，能够快速剔除客户端
    eviction-interval-timer-in-ms: 10000
info:
  app:
#  项目名称
    name: "@project.name@"
    description: "@project.description@"
    spring-boot-version: "@project.parent.version@"
  build:
    version: "@project.version@"