eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8006
spring:
  application:
    name: lfp-feign
hystrix:
  metrics:
    enabled: true
  command:
      default:
        execution:
          isolation:
            strategy: SEMAPHORE
management:
  security:
    enabled: false
feign:
  client:
    config:
      feignName:
        connectTimeout: 8000
        readTimeout: 10000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
        requestInterceptors:
          - com.hytch.lfpfeign.interceptor.ParamsInterceptor
          - com.hytch.lfpfeign.interceptor.ParamsInterceptor1
        decode404: false
feign.hystrix.enabled: true

info:
  app:
#  项目名称
    name: "@project.name@"
    description: "@project.description@"
    spring-boot-version: "@project.parent.version@"
  build:
    version: "@project.version@"