eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8006
spring:
  application:
    name: lfp-feign
hystrix:
  metrics:
    enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
feign.hystrix.enabled: true