spring:
  application:
    name: lfp-admin-cloud-server
server:
  port: 8001
#  增加登录验证的用户名和密码
security:
  user:
    name: lfp
    password: lfp123
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
info:
  app:
#  项目名称
    name: "@project.name@"
    description: "@project.description@"
    spring-boot-version: "@project.parent.version@"
  build:
    version: "@project.version@"
